branches:
  only: master

language: node_js

node_js:
  - 4
  - 5
  - stable

os: linux

env:
  - TARGET_REACT_VERSION=0.14
  - TARGET_REACT_VERSION=15

after_install:
  - npm uninstall react react-dom
  - npm install react@$(echo $TARGET_REACT_VERSION)
  - npm install react-dom@$(echo $TARGET_REACT_VERSION)

script:
  - npm test -- --coverage
  - codecov
