[install]
minimumReleaseAge = 259200                             # 3d
minimumReleaseAgeExcludes = ["markdown-to-jsx-latest"]

[run]
bun = true

[test]
preload = ["./lib/src/__mocks__/react-native.ts"]
